### ISSUE TITLE
docs for `rockcraft clean`

### ISSUE THREAD

**Issue by cjdcordeiro** [canonical/rockcraft#101]
thanks for the PR.

could you please create the docs for it? and for future PRs, it is easier to stay on track if we don't merge without the corresponding docs (otherwise some poor soul will have to, later on, spend hours on digging and writing existing features :p )

_Originally posted by @cjdcordeiro in https://github.com/canonical/rockcraft/issues/93#issuecomment-1261140164_

**Comment by mr-cal** [comment]
Yes, I'll add it to the docs!
