### ISSUE TITLE
Use Chisel `main` branch for Spread tests

### ISSUE THREAD

**Issue by cjdcordeiro** [canonical/rockcraft#162]
We're temporarily using a development branch in [docs/how-to/code/create-slice/task.yaml](https://github.com/canonical/rockcraft/pull/153/files/123cf4aa31d908f55c958d18ef6c95dabf391a23#diff-11e0033250351fc520ac0970830ea8ca98ed9e6485e59cb0bd680ac3d344d7b3), due to an existing bug.

Once https://github.com/canonical/chisel/pull/36 is merged, we can switch back to Chisel's main branch

**Comment by SamirPS** [comment]
Hey, 

I think this issue can be closed because now, if I search for git clone, I only see that we clone for the main branch of chisel, and the https://github.com/canonical/chisel/pull/36 is merged.
