### ISSUE TITLE
Using the pebble field "on-failure" doesn't work

### ISSUE THREAD

**Issue by gruyaume** [canonical/rockcraft#234]
### Overview

When trying to build a pebble Layer with the "on-failure" field, we get the following error message:

```
cannot parse layer "nginx": yaml: unmarshal errors:
  line 10: field on_failure not found in type plan.Service
```

This was tested with the [nginx-rock](https://github.com/canonical/nginx-rock/pull/6)

**Comment by cjdcordeiro** [comment]
Will be fixed via https://github.com/canonical/rockcraft/issues/235

Closing as duplicate
