### ISSUE TITLE
Available site packages depend on where python was loaded from

### ISSUE THREAD

**Issue by sed-i** [canonical/rockcraft#242]
I have a rockcraft.yaml that uses `python-packages`, and the packages end up in the rock, but a naive call to `python3` doesn't work. I have to use `/bin/python3`:

```
$ docker run --rm -it xgboostserver:1.16.0 exec python3 -c "import numpy as np; print(np)"     
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'

$ docker run --rm -it xgboostserver:1.16.0 exec /bin/python3 -c "import numpy as np; print(np)"
<module 'numpy' from '/lib/python3.8/site-packages/numpy/__init__.py'>
```

**Comment by tigarmo** [comment]
This is fixed by #248 ; now all Python packages provided by the part (including `python-packages` and those in `stage-packages`) should be usable regardless of interpreter-invocation-manner.
