### ISSUE TITLE
docs: rockcraft.yaml reference 

### ISSUE THREAD

**Issue by shipperizer** [canonical/rockcraft#297]
### Bug Description

Missing reference for the `organize` field in the `rockcraft.yaml`

The field [here](https://github.com/canonical/prometheus-rock/blob/main/rockcraft.yaml#L38)  is not really documented 

### To Reproduce

Click on the "here" hyperlink 

### Environment

all

### rockcraft.yaml

```shell
See link
```

### Relevant log output

```shell
See link
```

**Comment by tigarmo** [comment]
Hi! All subfields of `parts` come from the craft-parts library. We're working on integrating that documentation into our own reference, but in the meantime you can use [craft-parts' docs](https://canonical-craft-parts.readthedocs-hosted.com/en/latest/reference/part_properties.html#organize) directly.
