### ISSUE TITLE
Rebase "rockcraft pack" onto craft-application framework

### ISSUE THREAD

**Issue by lengau** [canonical/rockcraft#316]
### What needs to get done

The craft-application framework reduces repeated code from various *craft applications. Rockcraft should be rebased onto craft-application before we get a stable release.

### Why it needs to get done

Reduce repeated code throughout the *craft applications.

**Comment by tigarmo** [comment]
Renamed this issue to emphasize the fact that the work in progress is focused on making "rockcraft pack" work (with most bells and whistles except `--destructive` mode).

**Comment by tigarmo** [comment]
This was merged in #354 , but to the feature-branch
