### ISSUE TITLE
Migrate non-lifecycle commands to craft-application

### ISSUE THREAD

**Issue by tigarmo** [canonical/rockcraft#360]
### What needs to get done

Migrate the extensions and the `init` command to craft-application.

### Why it needs to get done

For parity!

**Comment by sergiusens** [comment]
This one might be a bit tricky as we need to consider specialization, which we are just getting into (like that --flask-framework option)

**Comment by tigarmo** [comment]
Actually I think it's straightforward because craft-application doesn't have an `init` command: the migration here is basically changing the superclass of the existing `InitCommand` in Rockcraft from `BaseCommand` to `AppCommand` and putting it in the correct CommandGroup
