### ISSUE TITLE
Cannot find current boot ID error on Google Cloud Run

### ISSUE THREAD

**Issue by gruyaume** [canonical/rockcraft#377]
### Bug Description

I'm trying to run a rockcraft build ROCK on Google Cloud Run and I'm getting the following error:

```
fatal: cannot find current boot ID: open /proc/sys/kernel/random/boot_id: no such file or directory
```

### To Reproduce

1. Create a Cloud Run service with the following container image: northamerica-northeast1-docker.pkg.dev/cognitive-profile/containers/cognitive-profile:0.1.0

### Environment

- Run environment: Google Cloud Run
- Rockcraft: rockcraft (edge) 0+git.cc7e3af

### rockcraft.yaml

```shell
name: cognitive-profile
base: ubuntu:22.04
version: "0.1.0"
summary: Cognitive Profile
description: |
  A tool for neuropsychologists to visualize cognitive profiles.
license: Apache-2.0
platforms:
  amd64:

package-repositories:
  - type: apt
    components: [main]
    priority: always
    suites: [nodistro]
    key-id: 6F71F525282841EEDAF851B42F59B5F99B1BE0B4
    key-server: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    url: https://deb.nodesource.com/node_18.x

services:
  cognitive-profile:
    command: npm run start
    override: replace
    startup: enabled
    working-dir: app

parts:

  cognitive-profile:
    plugin: nil
    source: .
    stage-packages:
      - nodejs
    build-snaps:
      - node/18/stable
    override-build: |
      mkdir -p ${CRAFT_PART_INSTALL}/app
      
      npm ci
      npm run build
      
      cp -r .next ${CRAFT_PART_INSTALL}/app/
      cp -r node_modules ${CRAFT_PART_INSTALL}/app/
      cp package.json ${CRAFT_PART_INSTALL}/app/
```

### Relevant log output

```shell
cannot run pebble: fatal: cannot find current boot ID: open /proc/sys/kernel/random/boot_id: no such file or directory
```

**Comment by gruyaume** [comment]
I'm realising this may be more of a Pebble issue than a rockcraft one

**Comment by cjdcordeiro** [comment]
interesting. At first glance it [does look Pebble-related](https://github.com/search?q=repo%3Acanonical%2Fpebble%20boot_id&type=code). I'm guessing the environment in which these runs are deployed (Google) also make a difference, as one would normally expect `/proc` to be mounted in the containers -> `docker run --rm ubuntu cat /proc/sys/kernel/random/boot_id`.

I remember @flotter was looking into something similar in Pebble some time ago, so maybe he has some additional insight as to why this could be happening and why Pebble needs/uses it.

**Comment by gruyaume** [comment]
I created an issue in pebble so that it is tracked at the right place:
- https://github.com/canonical/pebble/issues/317
