### ISSUE TITLE
rockcraft.yaml example contains `arm` key instead of `armhf`

### ISSUE THREAD

**Issue by gruyaume** [canonical/rockcraft#399]
### Request type

Fix

### What needs to get done

Replace `arm` with `armhf` in rockcraft.yaml example

### Documentation location

https://canonical-rockcraft.readthedocs-hosted.com/en/latest/reference/rockcraft.yaml/

### Additional information

The example does not work as is. Copy/pasting the example and building the rock results in an error.

**Comment by tigarmo** [comment]
Very true, thanks for reporting.
What we should do is add that example project to the spread tests, to ensure it's always buildable.
