### ISSUE TITLE
Upgrade skopeo version for docker engine API version

### ISSUE THREAD

**Issue by Guillaumebeuzeboc** [canonical/rockcraft#490]
### Bug Description

The current version of skopeo (v1.9.0) shipped with rockcraft is incompatible with the latest docker engine API version.
Calling skopeo to copy an OCI image into the docker-daemon gives:
```
FATA[0000] writing blob: saving image to docker engine: Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
```

The current [docker release](https://docs.docker.com/engine/release-notes/25.0/) requires API version 1.24 minimum.

Using skopeo from source (v1.15.0) fixes the issue.

### To Reproduce

- Install docker on [Ubuntu](https://docs.docker.com/engine/install/ubuntu/)
- Install rockcraft stable.
- Call `/snap/rockcraft/current/bin/skopeo --insecure-policy copy oci-archive:my_rock_amd64.rock docker-daemon:my_rock:rock`
-   Gives the following error: `FATA[0000] writing blob: saving image to docker engine: Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version`

### Environment

- Ubuntu 20.04
- rockcraft 1.2.0
```
$docker version

Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:14:17 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:17 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### rockcraft.yaml

```shell
Not relevant.
```

### Relevant log output

```shell
FATA[0000] writing blob: saving image to docker engine: Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
```

**Comment by tigarmo** [comment]
We actually [just merged](https://github.com/canonical/rockcraft/pull/477) an update to skopeo. On that PR we used version `1.14.2` as that is the latest released version on Github. Can you confirm whether that version also fixes the issue for you?

If it does, I'll make a `1.2.1` hotfix today as the update seems otherwise fine (regression-wise).
