### ISSUE TITLE
add unit tests for lifecycle.py

### ISSUE THREAD

**Issue by cjdcordeiro** [canonical/rockcraft#50]
`rockcraft/lifecycle.py` is missing a unit test. Despite it not having a lot of business logic to test, it is still worth having a unit test for it.

**Comment by mrn97** [comment]
Hi, @cjdcordeiro I checked `lifecycle.py` ,and I noticed two functions, you want to test both of them in one unit test file?

**Comment by cjdcordeiro** [comment]
> Hi, @cjdcordeiro I checked `lifecycle.py` ,and I noticed two functions, you want to test both of them in one unit test file?

Hi!

yes that's the goal. I suspect there will be a lot of fixture and mocks, since those functions mostly call out to other functions and modules that are already tested, but still, it would be nice to test all the possible `pack` paths of execution, to make sure the lifecycle behaves as expected

**Comment by SamirPS** [comment]
Do someone already has taken this issue ?

**Comment by cjdcordeiro** [comment]
nop. still unassigned afaik ;)

**Comment by cjdcordeiro** [comment]
done in https://github.com/canonical/rockcraft/commit/2f5b9c48321d3dce5dc0a2b17b0a27aceee6ec3c
