### ISSUE TITLE
"deleting current features configuration" ouput in every execution of Rockcraft

### ISSUE THREAD

**Issue by tigarmo** [canonical/rockcraft#585]
### Bug Description

There's an output of `deleting current features configuration` in every execution of Rockcraft, regardless of verbosity mode.

### To Reproduce

```
> ❯ rockcraft pack --verbosity=quiet
deleting current features configuration
Project file 'rockcraft.yaml' not found in '/home/tiago'. 
...
```

### Environment

rockcraft `1.3.2` running on Jammy

### rockcraft.yaml

```shell
.
```

### Relevant log output

```shell
.
```

**Comment by sergiusens** [comment]
https://github.com/canonical/rockcraft/blob/a110a87717399dbd6c9936bad57a5fde94505d34/rockcraft/services/lifecycle.py#L30
