### ISSUE TITLE
"Edit this page on GitHub" links broken

### ISSUE THREAD

**Issue by benhoyt** [canonical/rockcraft#780]
### Request type

Fix

### What needs to get done

For some reason the URL for the "Edit this page on GitHub" has some slashes removed. For example, https://documentation.ubuntu.com/rockcraft/en/latest/explanation/pebble/ links to https://github.com/canonical/rockcraft/edit/maindocsexplanation/pebble.rst instead of https://github.com/canonical/rockcraft/edit/main/docs/explanation/pebble.rst

### Documentation location

https://documentation.ubuntu.com/rockcraft/en/latest/explanation/pebble/

**Comment by tigarmo** [comment]
Thanks. It's a known issue unfortunately: https://github.com/canonical/rockcraft/issues/705
